/*
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.apis;

import com.appscode.voyager.client.ApiException;
import io.kubernetes.client.models.V1APIGroup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VoyagerAppscodeComApi
 */
@Ignore
public class VoyagerAppscodeComApiTest {

    private final VoyagerAppscodeComApi api = new VoyagerAppscodeComApi();

    
    /**
     * 
     *
     * get information of a group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIGroupTest() throws ApiException {
        V1APIGroup response = api.getAPIGroup();

        // TODO: test validations
    }
    
}
