/*
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.appscode.voyager.client.models.ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPIngressRuleValue;
import com.appscode.voyager.client.models.ComGithubAppscodeVoyagerApisVoyagerV1beta1TCPIngressRuleValue;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IngressRule represents the rules mapping the paths under a specified host to the related backend services. Incoming requests are first evaluated for a host match, then routed to the backend associated with the matching IngressRuleValue.
 */
@ApiModel(description = "IngressRule represents the rules mapping the paths under a specified host to the related backend services. Incoming requests are first evaluated for a host match, then routed to the backend associated with the matching IngressRuleValue.")

public class ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule {
  @SerializedName("host")
  private String host = null;

  @SerializedName("http")
  private ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPIngressRuleValue http = null;

  @SerializedName("tcp")
  private ComGithubAppscodeVoyagerApisVoyagerV1beta1TCPIngressRuleValue tcp = null;

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Host is the fully qualified domain name of a network host, as defined by RFC 3986. Note the following deviations from the \&quot;host\&quot; part of the URI as defined in the RFC: 1. IPs are not allowed. Currently an IngressRuleValue can only apply to the    IP in the Spec of the parent Ingress. 2. The &#x60;:&#x60; delimiter is not respected because ports are not allowed.    Currently the port of an Ingress is implicitly :80 for http and    :443 for https. Both these may change in the future. Incoming requests are matched against the host before the IngressRuleValue. If the host is unspecified, the Ingress routes all traffic based on the specified IngressRuleValue.
   * @return host
  **/
  @ApiModelProperty(value = "Host is the fully qualified domain name of a network host, as defined by RFC 3986. Note the following deviations from the \"host\" part of the URI as defined in the RFC: 1. IPs are not allowed. Currently an IngressRuleValue can only apply to the    IP in the Spec of the parent Ingress. 2. The `:` delimiter is not respected because ports are not allowed.    Currently the port of an Ingress is implicitly :80 for http and    :443 for https. Both these may change in the future. Incoming requests are matched against the host before the IngressRuleValue. If the host is unspecified, the Ingress routes all traffic based on the specified IngressRuleValue.")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule http(ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPIngressRuleValue http) {
    this.http = http;
    return this;
  }

   /**
   * Get http
   * @return http
  **/
  @ApiModelProperty(value = "")
  public ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPIngressRuleValue getHttp() {
    return http;
  }

  public void setHttp(ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPIngressRuleValue http) {
    this.http = http;
  }

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule tcp(ComGithubAppscodeVoyagerApisVoyagerV1beta1TCPIngressRuleValue tcp) {
    this.tcp = tcp;
    return this;
  }

   /**
   * Get tcp
   * @return tcp
  **/
  @ApiModelProperty(value = "")
  public ComGithubAppscodeVoyagerApisVoyagerV1beta1TCPIngressRuleValue getTcp() {
    return tcp;
  }

  public void setTcp(ComGithubAppscodeVoyagerApisVoyagerV1beta1TCPIngressRuleValue tcp) {
    this.tcp = tcp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule comGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule = (ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule) o;
    return Objects.equals(this.host, comGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule.host) &&
        Objects.equals(this.http, comGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule.http) &&
        Objects.equals(this.tcp, comGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule.tcp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, http, tcp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressRule {\n");
    
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    http: ").append(toIndentedString(http)).append("\n");
    sb.append("    tcp: ").append(toIndentedString(tcp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

