/*
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.appscode.voyager.client.models.ComGithubAppscodeVoyagerApisVoyagerV1beta1Ingress;
import com.appscode.voyager.client.models.V1ListMeta;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IngressList is a collection of Ingress.
 */
@ApiModel(description = "IngressList is a collection of Ingress.")

public class ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("items")
  private List<ComGithubAppscodeVoyagerApisVoyagerV1beta1Ingress> items = new ArrayList<ComGithubAppscodeVoyagerApisVoyagerV1beta1Ingress>();

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private V1ListMeta metadata = null;

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList items(List<ComGithubAppscodeVoyagerApisVoyagerV1beta1Ingress> items) {
    this.items = items;
    return this;
  }

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList addItemsItem(ComGithubAppscodeVoyagerApisVoyagerV1beta1Ingress itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Items is the list of Ingress.
   * @return items
  **/
  @ApiModelProperty(required = true, value = "Items is the list of Ingress.")
  public List<ComGithubAppscodeVoyagerApisVoyagerV1beta1Ingress> getItems() {
    return items;
  }

  public void setItems(List<ComGithubAppscodeVoyagerApisVoyagerV1beta1Ingress> items) {
    this.items = items;
  }

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList metadata(V1ListMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Standard object&#39;s metadata. More info: http://releases.k8s.io/release-1.2/docs/devel/api-conventions.md#metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "Standard object's metadata. More info: http://releases.k8s.io/release-1.2/docs/devel/api-conventions.md#metadata")
  public V1ListMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(V1ListMeta metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList comGithubAppscodeVoyagerApisVoyagerV1beta1IngressList = (ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList) o;
    return Objects.equals(this.apiVersion, comGithubAppscodeVoyagerApisVoyagerV1beta1IngressList.apiVersion) &&
        Objects.equals(this.items, comGithubAppscodeVoyagerApisVoyagerV1beta1IngressList.items) &&
        Objects.equals(this.kind, comGithubAppscodeVoyagerApisVoyagerV1beta1IngressList.kind) &&
        Objects.equals(this.metadata, comGithubAppscodeVoyagerApisVoyagerV1beta1IngressList.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, items, kind, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubAppscodeVoyagerApisVoyagerV1beta1IngressList {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

