/*
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.appscode.voyager.client.models.ComGithubAppscodeVoyagerApisVoyagerV1beta1LocalTypedReference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider
 */

public class ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider {
  @SerializedName("ingress")
  private ComGithubAppscodeVoyagerApisVoyagerV1beta1LocalTypedReference ingress = null;

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider ingress(ComGithubAppscodeVoyagerApisVoyagerV1beta1LocalTypedReference ingress) {
    this.ingress = ingress;
    return this;
  }

   /**
   * Get ingress
   * @return ingress
  **/
  @ApiModelProperty(value = "")
  public ComGithubAppscodeVoyagerApisVoyagerV1beta1LocalTypedReference getIngress() {
    return ingress;
  }

  public void setIngress(ComGithubAppscodeVoyagerApisVoyagerV1beta1LocalTypedReference ingress) {
    this.ingress = ingress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider comGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider = (ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider) o;
    return Objects.equals(this.ingress, comGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider.ingress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ingress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubAppscodeVoyagerApisVoyagerV1beta1HTTPChallengeProvider {\n");
    
    sb.append("    ingress: ").append(toIndentedString(ingress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

