/*
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.appscode.voyager.client.models.ComGithubAppscodeVoyagerApisVoyagerV1beta1BasicAuth;
import com.appscode.voyager.client.models.ComGithubAppscodeVoyagerApisVoyagerV1beta1TLSAuth;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ComGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption
 */

public class ComGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption {
  @SerializedName("basic")
  private ComGithubAppscodeVoyagerApisVoyagerV1beta1BasicAuth basic = null;

  @SerializedName("tls")
  private ComGithubAppscodeVoyagerApisVoyagerV1beta1TLSAuth tls = null;

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption basic(ComGithubAppscodeVoyagerApisVoyagerV1beta1BasicAuth basic) {
    this.basic = basic;
    return this;
  }

   /**
   * Get basic
   * @return basic
  **/
  @ApiModelProperty(value = "")
  public ComGithubAppscodeVoyagerApisVoyagerV1beta1BasicAuth getBasic() {
    return basic;
  }

  public void setBasic(ComGithubAppscodeVoyagerApisVoyagerV1beta1BasicAuth basic) {
    this.basic = basic;
  }

  public ComGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption tls(ComGithubAppscodeVoyagerApisVoyagerV1beta1TLSAuth tls) {
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @ApiModelProperty(value = "")
  public ComGithubAppscodeVoyagerApisVoyagerV1beta1TLSAuth getTls() {
    return tls;
  }

  public void setTls(ComGithubAppscodeVoyagerApisVoyagerV1beta1TLSAuth tls) {
    this.tls = tls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption comGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption = (ComGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption) o;
    return Objects.equals(this.basic, comGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption.basic) &&
        Objects.equals(this.tls, comGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption.tls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basic, tls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubAppscodeVoyagerApisVoyagerV1beta1AuthOption {\n");
    
    sb.append("    basic: ").append(toIndentedString(basic)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

