/*
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.appscode.voyager.client.models.IoK8sApimachineryPkgApisMetaV1Time;
import com.appscode.voyager.client.models.V1beta1ACMECertificateDetails;
import com.appscode.voyager.client.models.V1beta1CertificateCondition;
import com.appscode.voyager.client.models.V1beta1CertificateDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1CertificateStatus
 */

public class V1beta1CertificateStatus {
  @SerializedName("acmeUserSecretName")
  private String acmeUserSecretName = null;

  @SerializedName("certificateObtained")
  private Boolean certificateObtained = null;

  @SerializedName("conditions")
  private List<V1beta1CertificateCondition> conditions = null;

  @SerializedName("creationTime")
  private IoK8sApimachineryPkgApisMetaV1Time creationTime = null;

  @SerializedName("details")
  private V1beta1ACMECertificateDetails details = null;

  @SerializedName("lastIssuedCertificate")
  private V1beta1CertificateDetails lastIssuedCertificate = null;

  @SerializedName("message")
  private String message = null;

  public V1beta1CertificateStatus acmeUserSecretName(String acmeUserSecretName) {
    this.acmeUserSecretName = acmeUserSecretName;
    return this;
  }

   /**
   * Deprecated
   * @return acmeUserSecretName
  **/
  @ApiModelProperty(value = "Deprecated")
  public String getAcmeUserSecretName() {
    return acmeUserSecretName;
  }

  public void setAcmeUserSecretName(String acmeUserSecretName) {
    this.acmeUserSecretName = acmeUserSecretName;
  }

  public V1beta1CertificateStatus certificateObtained(Boolean certificateObtained) {
    this.certificateObtained = certificateObtained;
    return this;
  }

   /**
   * Deprecated
   * @return certificateObtained
  **/
  @ApiModelProperty(value = "Deprecated")
  public Boolean isCertificateObtained() {
    return certificateObtained;
  }

  public void setCertificateObtained(Boolean certificateObtained) {
    this.certificateObtained = certificateObtained;
  }

  public V1beta1CertificateStatus conditions(List<V1beta1CertificateCondition> conditions) {
    this.conditions = conditions;
    return this;
  }

  public V1beta1CertificateStatus addConditionsItem(V1beta1CertificateCondition conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<V1beta1CertificateCondition>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @ApiModelProperty(value = "")
  public List<V1beta1CertificateCondition> getConditions() {
    return conditions;
  }

  public void setConditions(List<V1beta1CertificateCondition> conditions) {
    this.conditions = conditions;
  }

  public V1beta1CertificateStatus creationTime(IoK8sApimachineryPkgApisMetaV1Time creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @ApiModelProperty(value = "")
  public IoK8sApimachineryPkgApisMetaV1Time getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(IoK8sApimachineryPkgApisMetaV1Time creationTime) {
    this.creationTime = creationTime;
  }

  public V1beta1CertificateStatus details(V1beta1ACMECertificateDetails details) {
    this.details = details;
    return this;
  }

   /**
   * Deprecated
   * @return details
  **/
  @ApiModelProperty(value = "Deprecated")
  public V1beta1ACMECertificateDetails getDetails() {
    return details;
  }

  public void setDetails(V1beta1ACMECertificateDetails details) {
    this.details = details;
  }

  public V1beta1CertificateStatus lastIssuedCertificate(V1beta1CertificateDetails lastIssuedCertificate) {
    this.lastIssuedCertificate = lastIssuedCertificate;
    return this;
  }

   /**
   * Get lastIssuedCertificate
   * @return lastIssuedCertificate
  **/
  @ApiModelProperty(value = "")
  public V1beta1CertificateDetails getLastIssuedCertificate() {
    return lastIssuedCertificate;
  }

  public void setLastIssuedCertificate(V1beta1CertificateDetails lastIssuedCertificate) {
    this.lastIssuedCertificate = lastIssuedCertificate;
  }

  public V1beta1CertificateStatus message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Deprecated
   * @return message
  **/
  @ApiModelProperty(value = "Deprecated")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1CertificateStatus v1beta1CertificateStatus = (V1beta1CertificateStatus) o;
    return Objects.equals(this.acmeUserSecretName, v1beta1CertificateStatus.acmeUserSecretName) &&
        Objects.equals(this.certificateObtained, v1beta1CertificateStatus.certificateObtained) &&
        Objects.equals(this.conditions, v1beta1CertificateStatus.conditions) &&
        Objects.equals(this.creationTime, v1beta1CertificateStatus.creationTime) &&
        Objects.equals(this.details, v1beta1CertificateStatus.details) &&
        Objects.equals(this.lastIssuedCertificate, v1beta1CertificateStatus.lastIssuedCertificate) &&
        Objects.equals(this.message, v1beta1CertificateStatus.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acmeUserSecretName, certificateObtained, conditions, creationTime, details, lastIssuedCertificate, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1CertificateStatus {\n");
    
    sb.append("    acmeUserSecretName: ").append(toIndentedString(acmeUserSecretName)).append("\n");
    sb.append("    certificateObtained: ").append(toIndentedString(certificateObtained)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    lastIssuedCertificate: ").append(toIndentedString(lastIssuedCertificate)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

