/*
 * Voyager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v7.1.1
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1OAuth
 */

public class V1beta1OAuth {
  @SerializedName("authBackend")
  private String authBackend = null;

  @SerializedName("authPath")
  private String authPath = null;

  @SerializedName("host")
  private String host = null;

  @SerializedName("paths")
  private List<String> paths = null;

  @SerializedName("signinPath")
  private String signinPath = null;

  public V1beta1OAuth authBackend(String authBackend) {
    this.authBackend = authBackend;
    return this;
  }

   /**
   * Get authBackend
   * @return authBackend
  **/
  @ApiModelProperty(value = "")
  public String getAuthBackend() {
    return authBackend;
  }

  public void setAuthBackend(String authBackend) {
    this.authBackend = authBackend;
  }

  public V1beta1OAuth authPath(String authPath) {
    this.authPath = authPath;
    return this;
  }

   /**
   * Get authPath
   * @return authPath
  **/
  @ApiModelProperty(value = "")
  public String getAuthPath() {
    return authPath;
  }

  public void setAuthPath(String authPath) {
    this.authPath = authPath;
  }

  public V1beta1OAuth host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @ApiModelProperty(value = "")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public V1beta1OAuth paths(List<String> paths) {
    this.paths = paths;
    return this;
  }

  public V1beta1OAuth addPathsItem(String pathsItem) {
    if (this.paths == null) {
      this.paths = new ArrayList<String>();
    }
    this.paths.add(pathsItem);
    return this;
  }

   /**
   * Get paths
   * @return paths
  **/
  @ApiModelProperty(value = "")
  public List<String> getPaths() {
    return paths;
  }

  public void setPaths(List<String> paths) {
    this.paths = paths;
  }

  public V1beta1OAuth signinPath(String signinPath) {
    this.signinPath = signinPath;
    return this;
  }

   /**
   * Get signinPath
   * @return signinPath
  **/
  @ApiModelProperty(value = "")
  public String getSigninPath() {
    return signinPath;
  }

  public void setSigninPath(String signinPath) {
    this.signinPath = signinPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1OAuth v1beta1OAuth = (V1beta1OAuth) o;
    return Objects.equals(this.authBackend, v1beta1OAuth.authBackend) &&
        Objects.equals(this.authPath, v1beta1OAuth.authPath) &&
        Objects.equals(this.host, v1beta1OAuth.host) &&
        Objects.equals(this.paths, v1beta1OAuth.paths) &&
        Objects.equals(this.signinPath, v1beta1OAuth.signinPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authBackend, authPath, host, paths, signinPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1OAuth {\n");
    
    sb.append("    authBackend: ").append(toIndentedString(authBackend)).append("\n");
    sb.append("    authPath: ").append(toIndentedString(authPath)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    signinPath: ").append(toIndentedString(signinPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

