/*
 * voyager-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.appscode.voyager.client.models.IoK8sApimachineryPkgApisMetaV1Time;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1CertificateCondition
 */

public class V1beta1CertificateCondition {
  @SerializedName("lastUpdateTime")
  private IoK8sApimachineryPkgApisMetaV1Time lastUpdateTime = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("type")
  private String type = null;

  public V1beta1CertificateCondition lastUpdateTime(IoK8sApimachineryPkgApisMetaV1Time lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
    return this;
  }

   /**
   * timestamp for the last update to this condition
   * @return lastUpdateTime
  **/
  @ApiModelProperty(value = "timestamp for the last update to this condition")
  public IoK8sApimachineryPkgApisMetaV1Time getLastUpdateTime() {
    return lastUpdateTime;
  }

  public void setLastUpdateTime(IoK8sApimachineryPkgApisMetaV1Time lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
  }

  public V1beta1CertificateCondition message(String message) {
    this.message = message;
    return this;
  }

   /**
   * human readable message with details about the request state
   * @return message
  **/
  @ApiModelProperty(value = "human readable message with details about the request state")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public V1beta1CertificateCondition reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * brief reason for the request state
   * @return reason
  **/
  @ApiModelProperty(value = "brief reason for the request state")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public V1beta1CertificateCondition type(String type) {
    this.type = type;
    return this;
  }

   /**
   * request approval state, currently Approved or Denied.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "request approval state, currently Approved or Denied.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1CertificateCondition v1beta1CertificateCondition = (V1beta1CertificateCondition) o;
    return Objects.equals(this.lastUpdateTime, v1beta1CertificateCondition.lastUpdateTime) &&
        Objects.equals(this.message, v1beta1CertificateCondition.message) &&
        Objects.equals(this.reason, v1beta1CertificateCondition.reason) &&
        Objects.equals(this.type, v1beta1CertificateCondition.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastUpdateTime, message, reason, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1CertificateCondition {\n");
    
    sb.append("    lastUpdateTime: ").append(toIndentedString(lastUpdateTime)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

