/*
 * Voyager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v7.1.1
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.appscode.voyager.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1DNSChallengeProvider
 */

public class V1beta1DNSChallengeProvider {
  @SerializedName("credentialSecretName")
  private String credentialSecretName = null;

  @SerializedName("provider")
  private String provider = null;

  public V1beta1DNSChallengeProvider credentialSecretName(String credentialSecretName) {
    this.credentialSecretName = credentialSecretName;
    return this;
  }

   /**
   * Get credentialSecretName
   * @return credentialSecretName
  **/
  @ApiModelProperty(value = "")
  public String getCredentialSecretName() {
    return credentialSecretName;
  }

  public void setCredentialSecretName(String credentialSecretName) {
    this.credentialSecretName = credentialSecretName;
  }

  public V1beta1DNSChallengeProvider provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * DNS Provider from the list https://github.com/appscode/voyager/blob/master/docs/tasks/certificate/providers.md
   * @return provider
  **/
  @ApiModelProperty(value = "DNS Provider from the list https://github.com/appscode/voyager/blob/master/docs/tasks/certificate/providers.md")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1DNSChallengeProvider v1beta1DNSChallengeProvider = (V1beta1DNSChallengeProvider) o;
    return Objects.equals(this.credentialSecretName, v1beta1DNSChallengeProvider.credentialSecretName) &&
        Objects.equals(this.provider, v1beta1DNSChallengeProvider.provider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credentialSecretName, provider);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1DNSChallengeProvider {\n");
    
    sb.append("    credentialSecretName: ").append(toIndentedString(credentialSecretName)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

